### ISSUE TITLE
Use Codeberg.org as secondary Mirror

### ISSUE THREAD

**Issue by fossdd** [nao20010128nao/ytdl-patched#18]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2021.03.03**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Codeberg.org is a non-profit gitea instance. Would nice if you could add this as a alternative mirror.

**Comment by nao20010128nao** [comment]
Thanks. I'll consider about it.

**Comment by nao20010128nao** [comment]
Yes, I accept your request and added as a new mirror.

Thanks for your suggestion.
